/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diskcollector.UI;

import diskcollector.Worker.FolderTreeReaderWorker;
import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 * Dialog per la gestione del log dello SwingWorker durante il caricamento
 * 
 * @author utente
 */
public class DlgSwingWorkerLog extends javax.swing.JDialog {

    FolderTreeReaderWorker folderTreeReaderWorker;
    
    long startTimeMillis,endTimeMillis;

    /**
     * Creates new form dlgSwingWorkerLog
     *
     * @param parent
     * @param modal
     * @param folderTreeReaderWorker
     */
    public DlgSwingWorkerLog(java.awt.Frame parent, boolean modal, FolderTreeReaderWorker folderTreeReaderWorker) {
        super(parent, modal);
        initComponents();
        this.folderTreeReaderWorker = folderTreeReaderWorker;
        this.folderTreeReaderWorker.setTextAreaLog(txtLogWorker);
        setLocationRelativeTo(parent);

        folderTreeReaderWorker.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent event) {

                // Se ho terminato il task aggiorno la UI
                if ("state".equals(event.getPropertyName()) && SwingWorker.StateValue.DONE.equals(event.getNewValue())) {
                    btnStopWorker.setText("Chiudi"); 
                    btnStopWorker.setBackground(Color.green);
                    
                    endTimeMillis=System.currentTimeMillis();
                    
                    txtLogWorker.append("\n\nTempo trascorso:");
                    txtLogWorker.append(String.valueOf((endTimeMillis-startTimeMillis)/1000));
                    txtLogWorker.append(" secondi\n");
                    
                    // Gestione tasto enter 
                    btnStopWorker.requestFocus();
                    getRootPane().setDefaultButton(btnStopWorker);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnStopWorker = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLogWorker = new javax.swing.JTextArea();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Creazione sottorami");

        btnStopWorker.setBackground(new java.awt.Color(255, 51, 51));
        btnStopWorker.setText("Ferma");
        btnStopWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopWorkerActionPerformed(evt);
            }
        });

        jLabel1.setText("Attività");

        txtLogWorker.setEditable(false);
        txtLogWorker.setColumns(20);
        txtLogWorker.setRows(5);
        jScrollPane1.setViewportView(txtLogWorker);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnStopWorker)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnStopWorker)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStopWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopWorkerActionPerformed
        if (folderTreeReaderWorker.isCancelled() || folderTreeReaderWorker.isDone()) {
            this.setVisible(false);
        } else {

            int val = JOptionPane.showConfirmDialog(this, "Annullo il caricamento?", "Conferma", JOptionPane.YES_NO_OPTION);
            if (val == JOptionPane.OK_OPTION) {
                folderTreeReaderWorker.cancel(true);
                btnStopWorker.setText("Chiudi");                 
            }
        }
    }//GEN-LAST:event_btnStopWorkerActionPerformed

    /**
     *
     */
    public void startWorkerAndShowDialog() {
        startTimeMillis=System.currentTimeMillis();
        folderTreeReaderWorker.execute();
        this.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStopWorker;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtLogWorker;
    // End of variables declaration//GEN-END:variables

}
